// src/components/HoverGif.jsx
import React from 'react';
import './../styles/HoverGif.css';

const HoverGif = ({ animation, frame, alt }) => {
  return (
    <div className="gif-container" style={{width: '100%', height: '100%'}}>
      <img
        className="gif-image static"
        src={frame}
        alt={alt}
      />
      <img
        className="gif-image animated"
        src={animation}
        alt={alt}
      />
    </div>
  );
};

export default HoverGif;

// src/app/components/hover-gif/hover-gif.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-hover-gif',
  imports: [],
  templateUrl: './hover-gif.component.html',
  styleUrl: './hover-gif.component.scss'
})
export class HoverGifComponent {
  @Input({ required: true }) animationSrc!: string;
  @Input({ required: true }) frameSrc!: string;
  @Input({ required: true }) alt!: string;
}

<div class="gif-container" style="width: 100%; height: 100%">
  <img class="gif-image static" [src]="frameSrc" [alt]="alt" />
  <img class="gif-image animated" [src]="animationSrc" [alt]="alt" />
</div>
